In [1]:
import pandas as pd

data=pd.read_excel('iptest.xlsx')
data.columns=['ip','age','gender','height','weight']
data=data[['ip']]
data

                  ip
0        120.26.0.11
1       118.31.1.154
2       47.92.155.21
3      221.226.75.86
4     153.101.67.170
..               ...
847  222.243.174.132
848   116.63.129.202
849      49.7.11.187
850   120.196.207.10
851     39.175.75.52

[852 rows x 1 columns]

In [2]:
data.drop_duplicates(subset=['ip'], inplace=True)
data

                  ip
0        120.26.0.11
1       118.31.1.154
2       47.92.155.21
3      221.226.75.86
4     153.101.67.170
..               ...
842   120.132.52.172
844  183.162.197.197
845   61.191.104.206
846  111.160.204.146
851     39.175.75.52

[226 rows x 1 columns]

In [3]:
data.to_excel('ip.xlsx')